name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rocq: ["9.0.1", "9.1.1"]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5.2.1
          dune-cache: true

      - name: Install opam dependencies
        run: |
          opam pin add --no-action --kind version rocq-core ${{ matrix.rocq }}
          opam install . --deps-only

      - name: Dune build
        run: opam exec -- dune build
